#!/usr/bin/env bash
#  Install nginx on your web-01 server
addlines="frontend http_web\n\tbind *:80\n\tmode http\n\tdefault_backend custom_backend\nbackend
custom_backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver
4219-web-01 54.88.102.174:80 check\n\tserver 4219-web-02 54.227.38.184:80 check"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo -e $addlines | sudo tee -a /etc/haproxy/haproxy.cfg
echo "web-01"
sudo service haproxy start